### ISSUE TITLE
ESP32 - can not write SD if Wifi lib linked

### ISSUE THREAD

**Issue by AurumVR** [nhatuan84/esp32_nanosdcard#5]
I'm using this lib for Lilygo-TTGO, where -due to a #@&#&@&# design of the board the standard SPI pins are inaccessible. When the wifi library is linked (no need of wifi.begin) opening a file for write always fails. Without wifi it works. Reading/deleting always works. I believe I'm good at finding solutions to random problems, but this is beyond me. Any ideas?

**Comment by Tsukay** [comment]
Hi,
I have the same issue, did you fixed it?
Where did you found this info?

**Comment by nhatuan84** [comment]
Maybe the power supply problem. Find the one with high power.

**Comment by AurumVR** [comment]
I tried wiring to different pins, powered the SD from a lab power supply, even messed around with the SPI settings.. but it gets too complicated for me after a while, digging myself deeper in the libs.. nothing. If wifi is linked, SD will not write.  Ultimately I'm gonna switch to a different board where the standard SPI is available.

**Comment by Tsukay** [comment]
I found the issue, it seems to be a redefinition in mySD wich make it uncompatible with WiFi.h
I used the exemple nanosdcard2 and everything worked well but just by including <WiFi.h> I can't write anything.
The link of the consol error : https://pastebin.com/LdfyHCwb

I know you don't support this library anymore but it's the only one I can use,  and I don't know how to modify the lib, can you update this issue please :)

You made an awsome job nhatuan84
Thank you

**Comment by Tsukay** [comment]
Ok i fixed it, i replaced every "O_******" by "F_******" in mySD.cpp, mySD.h and SdFile;cpp and now it's work great !

**Comment by Ed-Gordon** [comment]
I had to replace every O_ with F_  in 4 files to get it to work and write files:
mySD.cpp
mySD.h
SdFile.cpp
SdFat.h

Thanks Tsukay. I really like mySD and I could not figure out how I could make it work with WiFi.h

**Comment by nhatuan84** [comment]
> Ok i fixed it, i replaced every "O_******" by "F_******" in mySD.cpp, mySD.h and SdFile;cpp and now it's work great !

could you please upload your fix so that I can merge it to master. Thanks.

**Comment by Tsukay** [comment]
Hello, nhatuan84, I upload it few days ago but I didn't uploaded the fix for SdFat.h

**Comment by benhadad** [comment]
any update

**Comment by Tsukay** [comment]
the codes have been merged, it works
